### ISSUE TITLE
View sizeThatFits has no idea about options.

### ISSUE THREAD

**Issue by gabriel** [YOLayout/YOLayout#25]
If we are sizing to fit horizontal or vertical we call [view sizeThatFits:..] but it has no idea how its sizing (though usually vertical).

Options:
- Create new method sizeThatFits:options:
- If size.width is 0, then we are sizing horizontal, size.height is 0 then vertical. If we do this though, we can't set a max width or height and size to fit at the same time.

2nd option is easier and requires no work. We might want to do the first option down the road?

**Comment by johnboiles** [comment]
I think I like the first option the best. It's clearer what's happening.

**Comment by johnboiles** [comment]
This is pretty much the same as #15. That method would be the method on YOLayout, and `sizeThatFits:options:` would be the corresponding method on YOView.

**Comment by johnboiles** [comment]
Ended up adding this as a class method on `YOLayout`: `+ (CGSize)sizeThatFits:(CGSize)size view:(id)view options:(YOLayoutOptions)options`. Since there's no reason this needs the layout instance (frame is never set), this is fine as a class method. This also makes YOLayout less opinionated in that you can now use the internal layout tools, without needing to inherit from YOView.

**Comment by gabriel** [comment]
👍
